// tslint:disable no-var-requires
export default {
  "balloon-hook": require("./balloon-hook.svg"),
  "barstool": require("./barstool.svg"),
  "chef-head": require("./chef-head.svg"),
  "chef-outside": require("./chef-outside.svg"),
  "chef": require("./chef.svg"),
  "etienne-angry": require("./etienne-angry.svg"),
  "etienne-blush": require("./etienne-blush.svg"),
  "etienne-head": require("./etienne-head.svg"),
  "etienne-outside": require("./etienne-outside.svg"),
  "etienne-pee": require("./etienne-pee.svg"),
  "etienne": require("./etienne.svg"),
  "favicon": require("./favicon.svg"),
  "heart": require("./heart.svg"),
  "hob": require("./hob.svg"),
  "logo": require("./logo.svg"),
  "marie-angry": require("./marie-angry.svg"),
  "marie-blush": require("./marie-blush.svg"),
  "marie-head": require("./marie-head.svg"),
  "marie": require("./marie.svg"),
  "order-here": require("./order-here.svg"),
  "pager-active": require("./pager-active.svg"),
  "pager": require("./pager.svg"),
  "pan": require("./pan.svg"),
  "pause": require("./pause.svg"),
  "play": require("./play.svg"),
  "prep-times": require("./prep-times.svg"),
  "quick-logo": require("./quick-logo.svg"),
  "random-dude-angry": require("./random-dude-angry.svg"),
  "random-dude": require("./random-dude.svg"),
  "restart": require("./restart.svg"),
  "step-back": require("./step-back.svg"),
  "step-forward": require("./step-forward.svg"),
  "table": require("./table.svg"),
}