// tslint:disable no-var-requires
export default {
  "barstool": require("./barstool.svg"),
  "chef-head": require("./chef-head.svg"),
  "chef": require("./chef.svg"),
  "etienne-head": require("./etienne-head.svg"),
  "etienne": require("./etienne.svg"),
  "hob": require("./hob.svg"),
  "logo": require("./logo.svg"),
  "order-here": require("./order-here.svg"),
  "pan": require("./pan.svg"),
  "pause": require("./pause.svg"),
  "play": require("./play.svg"),
  "restart": require("./restart.svg"),
  "server-head": require("./server-head.svg"),
  "server": require("./server.svg"),
  "step-back": require("./step-back.svg"),
  "step-forward": require("./step-forward.svg"),
  "table": require("./table.svg"),
}